### ISSUE TITLE
[BUG] server connection error

### ISSUE THREAD

**Issue by jang-1996** [gume-gume/MLOps-project#75]
### ✔ 오류메시지

```
Traceback (most recent call last):
  File "/home/altu1996/MLOps-project/main.py", line 3, in <module>
    from app.routers import income
  File "/home/altu1996/MLOps-project/app/routers/income.py", line 7, in <module>
    from db.database import SessionLocal
  File "/home/altu1996/MLOps-project/db/database.py", line 11, in <module>
    conn = psycopg2.connect(host =settings.DB_ADDRESS ,
  File "/home/altu1996/miniconda3/envs/mlops/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### ✔ 버전정보
python 3.9.7

### ✔ 버그에 대한 뇌피셜

python main.py 를 실행하면 처음에는 위의 에러처럼 나오고 다시 한번 실행하였을 때 서버가 다시 켜졌습니다. 이에 대한 에러를 함께 공유하고자합니다.

**Comment by bigtrader91** [comment]
postgresql 의 포트랑 airflow 도커설치시의 포트랑 충돌하여 발생한 에러 갔습니다.

현재는 해결완료됐습니다.
