### ISSUE TITLE
[BUG] No module named 'airflow.providers.slack'

### ISSUE THREAD

**Issue by bigtrader91** [gume-gume/MLOps-project#92]
### ✔코드경로(line 포함)
- airflow slack 적용을 위한 테스트 도중 발생한 에러

### ✔ 오류메시지
```
Broken DAG: [/home/dahy949/airflow/project/dags/fail.py] Traceback (most recent call last):
  File "/home/dahy949/airflow/project/coin/slack.py", line 1, in <module>
    from airflow.operators.slack_operator import SlackAPIPostOperator
  File "/home/dahy949/miniconda3/lib/python3.9/site-packages/airflow/operators/slack_operator.py", line 22, in <module>
    from airflow.providers.slack.operators.slack import SlackAPIOperator, SlackAPIPostOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.slack'
```

### ✔ 버전정보
python 3.9.7
apache-airflow                  2.2.3
apache-airflow-providers-ftp    2.0.1
apache-airflow-providers-http   2.0.1
apache-airflow-providers-imap   2.0.1
apache-airflow-providers-slack  4.2.3
apache-airflow-providers-sqlite 2.0.1

### ✔ 버그에 대한 뇌피셜
airflow 와 slack 버전 차이로 인한 문제로 생각됨.

**Comment by bigtrader91** [comment]
airflow 삭제후 재설치 한 후에
비주얼스튜디오코드 재실행했더니 해결됐습니다.
