### ISSUE TITLE
[BUG] No module named 'slack_sdk'

### ISSUE THREAD

**Issue by bigtrader91** [gume-gume/MLOps-project#93]
### ✔코드경로(line 포함)
airflow  슬랙을 적용하려고 pip install slack-sdk 
했음에도 모듈을 인식 못함.

### ✔ 오류메시지
```
Broken DAG: [/home/dahy949/airflow/project/dags/coinflow.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dahy949/airflow/project/dags/coinflow.py", line 1, in <module>
    from slack_sdk import WebClient
ModuleNotFoundError: No module named 'slack_sdk'
```

### ✔ 버전정보
python 3.9.7

### ✔ 버그에 대한 뇌피셜
import 경로를 직접 지정해주는 방법을 찾아봐야할 것 같습니다.

**Comment by bigtrader91** [comment]
비주얼스튜디오코드 재실행 했더니 해결 됐습니다.
